name: caress_care
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^4.17.4
  firebase_core: ^2.30.0
  cloud_firestore:
  google_sign_in:
  provider:
  get:
  lottie:
  url_launcher:
  shared_preferences: ^2.5.3
  firebase_analytics: ^10.10.0
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  intl: ^0.20.2
  rename: ^3.1.0
  permission_handler: ^12.0.0+1
  image_picker: ^1.1.2
  flutter_animate: ^4.2.0
  flutter_svg: ^2.0.7
  firebase_storage: ^11.5.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_gen_runner:
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/calm_zone_logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/anim/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
